service: shipme
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

functions:
  login:
    handler: /v1/functions/login.handler
    events:
      - httpApi:
          path: /api/v1/login
          method: post
  register:
    handler: /v1/functions/register.handler
    events:
      - httpApi:
          path: /api/v1/register
          method: post
  verify:
    handler: /v1/functions/verify.handler
    events:
      - httpApi:
          path: /api/v1/verify
          method: post
  add-category:
    handler: /v1/functions/add-category.handler
    events:
      - httpApi:
          path: /api/v1/add-category
          method: post
  category:
    handler: /v1/functions/category.handler
    events:
      - httpApi:
          path: /api/v1/category
          method: get
  add-service-area:
    handler: /v1/functions/add-service-area.handler
    events:
      - httpApi:
          path: /api/v1/add-service-area
          method: post
  delivery-area:
    handler: /v1/functions/service-area.handler
    events:
      - httpApi:
          path: /api/v1/delivery-area
          method: get
  user-list:
    handler: /v1/functions/user-list.handler
    events:
      - httpApi:
          path: /api/v1/user-list
          method: get
  delete-user:
    handler: /v1/functions/delete-user.handler
    events:
      - httpApi:
          path: /api/v1/delete-user
          method: post
  delete-area:
    handler: /v1/functions/delete-area.handler
    events:
      - httpApi:
          path: /api/v1/delete-area
          method: post
  delete-category:
    handler: /v1/functions/delete-category.handler
    events:
      - httpApi:
          path: /api/v1/delete-category
          method: post
  edit-user:
    handler: /v1/functions/edit-user.handler
    events:
      - httpApi:
          path: /api/v1/edit-user
          method: post
  add-area:
    handler: /v1/functions/add-area.handler
    events:
      - httpApi:
          path: /api/v1/add-area
          method: post
  edit-area:
    handler: /v1/functions/edit-area.handler
    events:
      - httpApi:
          path: /api/v1/edit-area
          method: post
  # forgot:
  #   handler: /v1/auth/forgot-password.handler
  #   events:
  #     - httpApi:
  #         path: /api/v1/forgot
  #         method: post
  #         cors: true

plugins:
  - serverless-offline
